# Generated by Django 5.2.5 on 2025-08-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_searchhistory_viewhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewhistory',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
