services:
  db:
    image: mysql:8.0
    container_name: easyrent_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h ${DB_HOST} -p${DB_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: easyrent_app
    env_file:
      - .env
    ports:
      - "80:8000"
    command: >
      sh -c "python manage.py migrate \
      && python manage.py ensure_groups \
      && python manage.py collectstatic --noinput \
      && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

volumes:
  mysql_data: