services:
  db:
    image: mysql:8.0
    container_name: easyrent_db
#    env_file:
#      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h ${DB_HOST} -p${DB_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    build: .
    container_name: easyrent_migrate
    command: ["./migrate.sh"]
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app

  app:
    build: .
    container_name: easyrent_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G

volumes:
  mysql_data: